
# Exercise 9: Build an LSTM Model for Sentiment Classification 

## Aim

To build and evaluate a Long Short-Term Memory (LSTM) model for classifying text sentiment into Positive and Negative classes using deep learning techniques.

## Objectives

After completing this experiment, students will be able to: 
1. Understand the concept of Recurrent Neural Networks (RNN) and Long Short-Term Memory 
(LSTM).  
2. Perform text preprocessing using tokenization and padding.  
3. Convert text into numerical sequences suitable for deep learning models.  
4. Build an LSTM-based sentiment classification model using TensorFlow/Keras.  
5. Train and evaluate the LSTM model.  
6. Predict the sentiment of unseen text. 

## Pre-Lab Task:

#### Consider the following movie reviews. 
1. The product quality is excellent. 
2. I am very happy with the service. 
3. The delivery was very slow. 
4. The product is damaged. 
5. Excellent customer support. 
6. Very disappointed with the purchase.  

###   1. Assign appropriate sentiment labels
##### Movie Review	Sentiment
* The product quality is excellent.	Positive
* I am very happy with the service.	Positive
* The delivery was very slow.	Negative
* The product is damaged.	Negative
* Excellent customer support.	Positive
* Very disappointed with the purchase.	Negative

###   2. Train the LSTM model using the above reviews

######  A) The six reviews are tokenized and converted into numerical sequences. The sequences are padded to the same length and given to an LSTM model containing Embedding, LSTM, and Dense/Sigmoid layers.

###   3. Predict the sentiment

##### Input:

"The product is very good and easy to use."

##### Expected Output:

Predicted Sentiment: Positive

## In- Lab Task:


### Model Architecture 
| Layer         | Purpose                                      |
| ------------- | -------------------------------------------- |
| **Embedding** | Converts words into dense numerical vectors. |
| **LSTM**      | Learns the sequence and context of words.    |
| **Dense**     | Produces the final prediction.               |
| **Sigmoid**   | Outputs a probability between 0 and 1.       |
 

In [9]:
%pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [10]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.21.0


In [11]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# --------------------------------
# Step 1: Input Dataset
# --------------------------------

reviews = [
    "The product quality is excellent",
    "I am very happy with the service",
    "The delivery was very slow",
    "The product is damaged",
    "Excellent customer support",
    "Very disappointed with the purchase"
]

# Positive = 1, Negative = 0
labels = np.array([1, 1, 0, 0, 1, 0])

# --------------------------------
# Step 2: Tokenization
# --------------------------------

tokenizer = Tokenizer()
tokenizer.fit_on_texts(reviews)

sequences = tokenizer.texts_to_sequences(reviews)

print("Tokenized Sequences:")
print(sequences)

# --------------------------------
# Step 3: Padding
# --------------------------------

max_length = max(len(seq) for seq in sequences)

X = pad_sequences(
    sequences,
    maxlen=max_length,
    padding='post'
)

print("\nPadded Sequences:")
print(X)

# --------------------------------
# Step 4: Build LSTM Model
# --------------------------------

vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=16,
        input_length=max_length
    ),
    LSTM(32),
    Dense(1, activation='sigmoid')
])

# --------------------------------
# Step 5: Compile Model
# --------------------------------

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# --------------------------------
# Step 6: Train Model
# --------------------------------

model.fit(
    X,
    labels,
    epochs=100,
    verbose=0
)

print("\nLSTM model trained successfully.")

# --------------------------------
# Step 7: Predict New Review
# --------------------------------

new_review = ["The product is very good and easy to use"]

new_sequence = tokenizer.texts_to_sequences(new_review)

new_padded = pad_sequences(
    new_sequence,
    maxlen=max_length,
    padding='post'
)

prediction = model.predict(new_padded, verbose=0)[0][0]

print("\nNew Review:")
print(new_review[0])

print("Prediction Probability:", round(float(prediction), 4))

if prediction >= 0.5:
    print("Predicted Sentiment: Positive")
else:
    print("Predicted Sentiment: Negative")

Tokenized Sequences:
[[1, 3, 7, 4, 5], [8, 9, 2, 10, 6, 1, 11], [1, 12, 13, 2, 14], [1, 3, 4, 15], [5, 16, 17], [2, 18, 6, 1, 19]]

Padded Sequences:
[[ 1  3  7  4  5  0  0]
 [ 8  9  2 10  6  1 11]
 [ 1 12 13  2 14  0  0]
 [ 1  3  4 15  0  0  0]
 [ 5 16 17  0  0  0  0]
 [ 2 18  6  1 19  0  0]]

LSTM model trained successfully.

New Review:
The product is very good and easy to use
Prediction Probability: 0.0232
Predicted Sentiment: Negative


## Post-Lab Task:

###   1. How does the Embedding layer help an LSTM model?

##### A) The Embedding layer converts words into dense numerical vectors. These vectors capture relationships between words and provide meaningful numerical input for the LSTM.

###   2. What is the role of the LSTM layer in sentiment classification?

##### A) The LSTM layer learns the sequence and context of words in a sentence. It helps identify patterns that indicate whether a review is positive or negative.

###   3. State two advantages of using LSTM over a traditional RNN.
1. LSTM can remember long-term dependencies in sequences more effectively.
2. LSTM reduces the vanishing-gradient problem, making it easier to learn from long sequences.